### ISSUE TITLE
Convert from OBJ + MTL + textures to gLTF

### ISSUE THREAD

**Issue by nschapeler** [Esri/pyprt-examples#10]
As the title states, is there a way to use your library to convert from an Obj file along with an mtl file and textures to the gLTF format that conserves the tetxtures?

**Comment by clechot** [comment]
Hi!
Thx for your question.
This feature is not supported yet but is planned for a future release (https://github.com/Esri/pyprt/issues/8).
The only way at the moment would be to write your own CGA rule (RPK) to apply those materials and textures to the initial shape. To do so, you'll need CityEngine.

**Comment by nschapeler** [comment]
Thank you for the reply!
