### ISSUE TITLE
ex8_3d_gis_content_generation.ipynb: PRT generation

### ISSUE THREAD

**Issue by M-Bryant** [Esri/pyprt-examples#4]
I don't have permission to reach the RPK used in the example.
rpk = gis.content.get('2c31f077021b495cbfe4097227fdd78e')

Can all data used in the example be made publicly accessible.

**Comment by clechot** [comment]
Hello,

Thanks for the comment. It should be fixed now.

The Zurich Parks parcels Feature Layer ID has been changed in my last commit. You might want to checkout the example from the last master branch state.

**Comment by mistafunk** [comment]
We assume this is fixed - please reopen otherwise!
