### ISSUE TITLE
read fbx file with texture issure

### ISSUE THREAD

**Issue by RukunHsu** [Esri/pyprt-examples#78]
when i use pyprt to conver 3d models format(fbx to obj),there some issure with texture:
AssetWarning    0 'bin/formatchange.cgb' '' 'Potentially unsupported CGAC version 1.18 : newer than current (1.17)'
AssetWarning    0 '<initial shape geometry>' '' 'Failed to resolve texture with key 'file:/D://build_001//build_001.fbx/D:/build_001/texture/concrete_02_fine.jpg'
Failed to resolve texture with key 'file:/D://build_001//build_001.fbx/D:/build_001/texture/build_01.jpg'
Failed to resolve texture with key 'file:/D://build_001//build_001.fbx/D:/build_001/texture/concrete_02.jpg'
Failed to resolve texture with key 'file:/D://build_001//build_001.fbx/D:/build_001/texture/concrete_01.jpg'
Failed to resolve texture with key 'file:/D://build_001//build_001.fbx/D:/build_001/texture/concrete_02.jpg'
Failed to resolve texture with key 'file:/D://build_001//build_001.fbx/D:/build_001/texture/concrete_02_fine.jpg'

**Comment by RukunHsu** [comment]
I think this issure with wrong path of texture.

**Comment by mistafunk** [comment]
Sorry for the very late response.

Do I understand correctly, that you are trying to create a textured initial shape from an FBX asset and then want to encode it to OBJ?

If yes, this will be supported in upcoming release 1.7: https://github.com/Esri/pyprt/blob/0fa19da2a92409765edc7c22451cd6b8a85246a4/CHANGELOG.md?plain=1#L7

This feature is already merged to the `develop` branch if you want to try it out (needs manual building of PyPRT module though).

**Comment by mistafunk** [comment]
Released in 1.7
