### ISSUE TITLE
How to plot some 3d trees with different height using python.

### ISSUE THREAD

**Issue by jetsonwork** [Esri/pyprt-examples#83]
Hello Could you please let me whether it is possible to plot some 3d trees with different heights using python?

**Comment by mistafunk** [comment]
Hi! Yes, this is one of the core features of PyPRT.

One starting point is to author a rule which uses the plant loader helper provided by the [CityEngine ESRI.lib](https://doc.arcgis.com/en/cityengine/latest/help/help-esri-lib-webstyles.htm#ESRI_SECTION1_C573DC5AE8B846A59CAF24AE094688AB).

Then you can expose a "height" attribute in your rule which you can then drive from Python. How to set attributes is shown in [example 4](https://github.com/Esri/pyprt-examples/blob/9d15e74986ff0fad88f7e2d071c64a0af7420bcd/ex4_multi_generations.py#L40).

Hope that helps to get you started!

**Comment by mistafunk** [comment]
Closing this due to age - feel free to reopen are ask a new question :-)
